spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${MAIN_MYSQL_HOST:127.0.0.1}:${MAIN_DB_PORT:5432}/${MAIN_DB_NAME:dms-main-local}?reWriteBatchedInserts=true
    username: ${MAIN_MYSQL_USERNAME:postgres}
    password: ${MAIN_MYSQL_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:asdf}
