object DependencyVersions {
    const val JACKSON_VERSION = "2.16.1"
    const val JWT_VERSION = "0.11.5"
    const val AWS_VERSION = "2.4.4"
    const val SES_VERSION = "1.11.852"
    const val REDIS_VERSION = "2.7.2"
    const val SERVLET_VERSION = "6.0.0"
    const val UUID_TIME_VERSION = "3.1.4"
    const val SPRING_TRANSACTION_VERSION = "6.1.2"
    const val QUERYDSL_VERSION = "5.0.0"
    const val JAKARTA_ANNOTATION_VERSION = "2.1.1"
    const val JAKARTA_PERSISTENCE_VERSION = "3.1.0"
    const val POSTGRESQL = "42.7.13"

    // hibernate-vector 는 Spring Boot BOM 이 관리하지 않으므로, BOM 이 정하는 hibernate-core 와 같은 버전을 직접 맞춘다.
    // Boot 버전을 올리면 이 값도 함께 올려야 한다(어긋나면 #1108 과 같은 AbstractMethodError 가 난다).
    const val HIBERNATE_VERSION = "6.4.4.Final"
    const val APACHE_POI_VERSION = "3.7"
    const val MOCKK_VERSION = "1.13.10"
    const val SPRING_KOTEST_VERSION = "1.1.3"
    const val KOTEST_VERSION = "5.7.2"
    const val ASPECTJ_VERSION = "1.9.7"
    const val FCM_VERSION = "9.3.0"
    const val FLYWAY_VERSION = "10.8.1"
    const val SLACK_VERSION = "1.40.3"
    const val GRPC_VERSION = "1.60.0"
    const val GRPC_PROTOBUF_JAVA_VERSION = "3.21.12"
    const val RABBITMQ_VERSION = "3.2.3"
    const val SPRING_CLOUD_GATEWAY_VERSION = "4.1.0"
    const val OPEN_FEIGN_VERSION = "4.1.0"
    const val TESTCONTAINERS_VERSION = "1.19.3"
}