name: DMS - xquare deployment dev

on:
  push:
    branches:
      - main
      - develop
      
jobs:
  CD:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --build-cache
            --no-daemon

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: stag
          access_key: ${{ secrets.ACCESS_KEY }}
          buildargs: |
            PROFILE=dev
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            AWS_ACCESS=${{ secrets.AWS_ACCESS }}
            AWS_SECRET=${{ secrets.AWS_SECRET }}
            NEIS_KEY=${{ secrets.NEIS_KEY }}
            SES_SENDER=${{ secrets.SES_SENDER }}
            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            FCM_FILE_URL=${{ secrets.FCM_FILE_URL }}
            FLYWAY_ENABLED=${{ secrets.FLYWAY_ENABLED }}
            BASELINE_ON_MIGRATE=${{ secrets.BASELINE_ON_MIGRATE }}
#            SLACK_WEBHOOK_URL=${{ secrets.SLACK_STAG_WEBHOOK_URL }}